# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "astro207a"
region = "us-east-1"
profile = "myawsprofile"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
[default.local_start_lambda.parameters]
warm_containers = "EAGER"


[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
confirm_changeset = false
resolve_s3 = true
#stack_name = "astro-sam-202-oidc-customres"
#s3_bucket = "sam-clisourcebucket-btkyfgdhnica"

[default.deploy.parameters.parameter_overrides]
AppName = "cs-itp-ssg-cd-sam"
AuthorizedGithubRepository = "Codingschule/aws-astro-headless-cms-deployment"
OidcConnectorDeployment = "2"
CorsMode = "2" # allow localhost
AutoDeleteBucket = true