name: Deploy to AWS (OIDC)
on:
  push: # successfull merge is also a push
    branches: [ dev ]
  pull_request: # successfull merge is also a push
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'deploy.yml AND src from'
        default: 'dev'

jobs:
  build_and_maybe_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install and Build
        working-directory: ./frontend
        run: npm install && npm run build
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        if: github.event_name == 'push'
        run: aws s3 sync ./frontend/dist s3://${{ secrets.AWS_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        if: github.event_name == 'push'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_CLOUDFRONT_ID }} --paths "/*"
